<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_timesheet extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sdb_timesheet_model');
    } 

    /*
     * Listing of sdb_timesheets
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('sdb_timesheet/index?');
        $config['total_rows'] = $this->Sdb_timesheet_model->get_all_sdb_timesheets_count();
        $this->pagination->initialize($config);

        $data['sdb_timesheets'] = $this->Sdb_timesheet_model->get_all_sdb_timesheets($params);
        
        $data['_view'] = 'sdb_timesheet/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new sdb_timesheet
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'user_id' => $this->input->post('user_id'),
				'timesheet_time_month' => $this->input->post('timesheet_time_month'),
				'timesheet_day_checkin' => $this->input->post('timesheet_day_checkin'),
				'timesheet_day_total' => $this->input->post('timesheet_day_total'),
				'timesheet_createdate' => $this->input->post('timesheet_createdate'),
            );
            
            $sdb_timesheet_id = $this->Sdb_timesheet_model->add_sdb_timesheet($params);
            redirect('sdb_timesheet/index');
        }
        else
        {
			$this->load->model('Sdb_user_model');
			$data['all_sdb_user'] = $this->Sdb_user_model->get_all_sdb_user();
            
            $data['_view'] = 'sdb_timesheet/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a sdb_timesheet
     */
    function edit($timesheet_id)
    {   
        // check if the sdb_timesheet exists before trying to edit it
        $data['sdb_timesheet'] = $this->Sdb_timesheet_model->get_sdb_timesheet($timesheet_id);
        
        if(isset($data['sdb_timesheet']['timesheet_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'user_id' => $this->input->post('user_id'),
					'timesheet_time_month' => $this->input->post('timesheet_time_month'),
					'timesheet_day_checkin' => $this->input->post('timesheet_day_checkin'),
					'timesheet_day_total' => $this->input->post('timesheet_day_total'),
					'timesheet_createdate' => $this->input->post('timesheet_createdate'),
                );

                $this->Sdb_timesheet_model->update_sdb_timesheet($timesheet_id,$params);            
                redirect('sdb_timesheet/index');
            }
            else
            {
				$this->load->model('Sdb_user_model');
				$data['all_sdb_user'] = $this->Sdb_user_model->get_all_sdb_user();

                $data['_view'] = 'sdb_timesheet/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The sdb_timesheet you are trying to edit does not exist.');
    } 

    /*
     * Deleting sdb_timesheet
     */
    function remove($timesheet_id)
    {
        $sdb_timesheet = $this->Sdb_timesheet_model->get_sdb_timesheet($timesheet_id);

        // check if the sdb_timesheet exists before trying to delete it
        if(isset($sdb_timesheet['timesheet_id']))
        {
            $this->Sdb_timesheet_model->delete_sdb_timesheet($timesheet_id);
            redirect('sdb_timesheet/index');
        }
        else
            show_error('The sdb_timesheet you are trying to delete does not exist.');
    }
    
}
