<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Sdb_station extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sdb_station_model');
        $this->load->model('Sdb_location_model');
        $this->load->model('Sdb_distance_model');
        $this->load->model('Sdb_station_status_model');

    } 

    /*
     * Listing of sdb_stations
     */
    function index()
    {
        $params['limit'] = 15; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        $config = $this->config->item('pagination');
        $config['per_page'] = 15;
        $config['base_url'] = site_url('sdb_station/index?');
        $config['total_rows'] = $this->Sdb_station_model->get_all_sdb_stations_count();
        
        $this->pagination->initialize($config);

        $data['sdb_stations'] = $this->Sdb_station_model->get_all_sdb_stations($params);
        
        $data['_view'] = 'sdb_station/index';
        $this->load->view('layouts/main',$data);
    }


    function add()
    {

        $this->load->library('form_validation');
        
        $this->form_validation->set_rules('location_id','Location Id','required|integer');
        $this->form_validation->set_rules('station_name','Station Name','required|max_length[200]');
        $this->form_validation->set_rules('station_note','Station Note','required|max_length[500]');
        $this->form_validation->set_rules('location_id','location ','required');
        // $this->form_validation->set_rules('station_location','Station Location','required|max_length[200]');

        $img_link = '';
        if($this->form_validation->run())     
        {   

            if($_FILES['station_img']['name'] !== '') {
                $img_upload = $this->my_system->upload_img('station_img','./uploads/stations');
                if(!$img_upload['status'] ) {
                 $data['error'] = $img_upload['message'];
                 $data['all_sdb_location'] = $this->Sdb_location_model->get_all_sdb_location();
                 $data['all_sdb_distance'] = $this->Sdb_distance_model->get_all_sdb_distance();
                 $data['_view'] = 'sdb_station/add';
                 $this->load->view('layouts/main',$data);
                 return;
             }    
             $img_link = $img_upload['path_img'];
             $this->my_system->gd2_img($img_link);
         }


         $params = array(
            'station_active' => 1,
            'location_id' => $this->input->post('location_id'),
            'distance_id' => $this->input->post('distance_id'),
            'station_name' => $this->input->post('station_name'),
            'station_note' => $this->input->post('station_note'),
            // 'station_location' => $this->input->post('station_location'),
            'lenght' => $this->input->post('lenght'),
            'width' => $this->input->post('width'),
            'km_start' => $this->input->post('km_start'),
            'km_end' => $this->input->post('km_end'),
            'start_lat' => 1,
            'start_long' => 1,
            'end_lat' => 1,
            'end_lng' => 1,
            'station_img' => $img_link
        );

         $sdb_station_id = $this->Sdb_station_model->add_sdb_station($params);
         redirect('sdb_station/index');
     } else {
        $data['all_sdb_location'] = $this->Sdb_location_model->get_all_sdb_location();
        $data['all_sdb_distance'] = $this->Sdb_distance_model->get_all_sdb_distance();
        $data['all_sdb_station_status'] = $this->Sdb_station_status_model->get_all_sdb_station_status();

        $data['_view'] = 'sdb_station/add';
        $this->load->view('layouts/main',$data);
    }
}



function edit($station_id)
{   

    $data['sdb_station'] = $this->Sdb_station_model->get_sdb_station($station_id);

    if(isset($data['sdb_station']['station_id']))
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('station_active','Station Active','required');
        $this->form_validation->set_rules('location_id','Location Id','required|integer');
        $this->form_validation->set_rules('station_name','Station Name','required|max_length[200]');
        $this->form_validation->set_rules('station_note','Station Note','required|max_length[500]');
        $this->form_validation->set_rules('station_location','Station Location','required|max_length[200]');
        $this->form_validation->set_rules('lenght','Lenght','required|numeric');
        $this->form_validation->set_rules('width','Width','required|numeric');

        if($this->form_validation->run())     
        {   
            $params = array(
             'station_active' => $this->input->post('station_active'),
             'location_id' => $this->input->post('location_id'),
             'station_name' => $this->input->post('station_name'),
             'station_note' => $this->input->post('station_note'),
             'station_location' => $this->input->post('station_location'),
             'lenght' => $this->input->post('lenght'),
             'width' => $this->input->post('width'),
             'start_lat' => 1,
             'start_long' => 1,
             'end_lat' => 1,
             'end_lng' => 1,
         );

            $this->Sdb_station_model->update_sdb_station($station_id,$params);            
            redirect('sdb_station/index');
        }
        else
        {
            $data['all_sdb_location'] = $this->Sdb_location_model->get_all_sdb_location();
            $data['_view'] = 'sdb_station/edit';
            $this->load->view('layouts/main',$data);
        }
    }
    else
        show_error('The sdb_station you are trying to edit does not exist.');
} 


function remove($station_id)
{
    $sdb_station = $this->Sdb_station_model->get_sdb_station_by_id($station_id);
    var_dump($sdb_station);
    if(isset($sdb_station['station_id']))
    {
        $this->Sdb_station_model->delete_sdb_station($station_id);
        redirect('sdb_station/index');
    }
    else
        show_error('The sdb_station you are trying to delete does not exist.');
}

function ajax_station_by_distance_get($distance_id = 0) {
    $this->load->model('Sdb_station_model');
    $reponse =  $this->Sdb_station_model->get_all_sdb_stations_by_distance($distance_id);
    $this->api_support->set_Reponse($reponse, 200 );
}


function ajax_station_by_checkin_distance($checkin_distance_id = 0) {
    $this->load->model('Sdb_station_model');
    $reponse =  $this->Sdb_station_model->get_all_sdb_stations_by_checkin_distance($checkin_distance_id);
    $this->api_support->set_Reponse($reponse, 200 );
}


private function upload_img($img_file)
{
    $config['upload_path']          = './uploads/stations';
    $config['allowed_types']        = 'gif|jpg|png';
    $config['max_size']             = 1000;
    $config['max_width']            = 1024;
    $config['max_height']           = 768;
    $this->load->library('upload', $config);
    if ( ! $this->upload->do_upload($img_file)) {
        $error = array('error' => $this->upload->display_errors());
        return ['status' => false , 'message'=> $error];
    } else {
        return  ['status' => true , 'message'=> 'uploads/stations/'.$this->upload->data()['file_name'] ] ;
    }
}
}
