<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_trouble_parents_type extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sdb_trouble_parents_type_model');
    } 

    /*
     * Listing of sdb_trouble_parents_type
     */
    function index()
    {
        $data['sdb_trouble_parents_type'] = $this->Sdb_trouble_parents_type_model->get_all_sdb_trouble_parents_type();
        
        $data['_view'] = 'sdb_trouble_parents_type/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new sdb_trouble_parents_type
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('trouble_parents_type_name','Trouble Parents Type Name','required|max_length[100]');
		// $this->form_validation->set_rules('trouble_parents_type_active','Trouble Parents Type Active','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'trouble_parents_type_name' => $this->input->post('trouble_parents_type_name'),
				'trouble_parents_type_active' => 1,
            );
            
            $sdb_trouble_parents_type_id = $this->Sdb_trouble_parents_type_model->add_sdb_trouble_parents_type($params);
            redirect('sdb_trouble_parents_type/index');
        }
        else
        {            
            $data['_view'] = 'sdb_trouble_parents_type/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a sdb_trouble_parents_type
     */
    function edit($trouble_parents_type_id)
    {   
        // check if the sdb_trouble_parents_type exists before trying to edit it
        $data['sdb_trouble_parents_type'] = $this->Sdb_trouble_parents_type_model->get_sdb_trouble_parents_type($trouble_parents_type_id);
        
        if(isset($data['sdb_trouble_parents_type']['trouble_parents_type_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('trouble_parents_type_name','Trouble Parents Type Name','required|max_length[100]');
			$this->form_validation->set_rules('trouble_parents_type_active','Trouble Parents Type Active','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'trouble_parents_type_name' => $this->input->post('trouble_parents_type_name'),
					'trouble_parents_type_active' => $this->input->post('trouble_parents_type_active'),
                );

                $this->Sdb_trouble_parents_type_model->update_sdb_trouble_parents_type($trouble_parents_type_id,$params);            
                redirect('sdb_trouble_parents_type/index');
            }
            else
            {
                $data['_view'] = 'sdb_trouble_parents_type/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The sdb_trouble_parents_type you are trying to edit does not exist.');
    } 

    /*
     * Deleting sdb_trouble_parents_type
     */
    function remove($trouble_parents_type_id)
    {
        $sdb_trouble_parents_type = $this->Sdb_trouble_parents_type_model->get_sdb_trouble_parents_type($trouble_parents_type_id);

        // check if the sdb_trouble_parents_type exists before trying to delete it
        if(isset($sdb_trouble_parents_type['trouble_parents_type_id']))
        {
            $this->Sdb_trouble_parents_type_model->delete_sdb_trouble_parents_type($trouble_parents_type_id);
            redirect('sdb_trouble_parents_type/index');
        }
        else
            show_error('The sdb_trouble_parents_type you are trying to delete does not exist.');
    }
    
}
