<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_comment_project extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sdb_comment_project_model');
    } 

    /*
     * Listing of sdb_comment_project
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('sdb_comment_project/index?');
        $config['total_rows'] = $this->Sdb_comment_project_model->get_all_sdb_comment_project_count();
        $this->pagination->initialize($config);

        $data['sdb_comment_project'] = $this->Sdb_comment_project_model->get_all_sdb_comment_project($params);
        
        $data['_view'] = 'sdb_comment_project/index';
        $this->load->view('layouts/main',$data);
    }
}
