<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Sdb_trouble_category extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sdb_trouble_category_model');
    } 

    /*
     * Listing of Sdb_trouble_category
     */
    function index()
    {


     $params['limit'] = RECORDS_PER_PAGE; 
     $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

     $config = $this->config->item('pagination');
     $config['base_url'] = site_url('sdb_trouble_category/index?');
     $config['total_rows'] = $this->Sdb_trouble_category_model->get_all_trouble_category_count();
       $this->pagination->initialize($config);

     $data['Sdb_trouble_category'] = $this->Sdb_trouble_category_model->get_all_trouble_category($params);

     $data['_view'] = 'sdb_trouble_category/index';
     $this->load->view('layouts/main',$data);
 }
}
