<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_task_type extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sdb_task_type_model');
    } 

    /*
     * Listing of sdb_task_type
     */
    function index()
    {
        $data['sdb_task_type'] = $this->Sdb_task_type_model->get_all_sdb_task_type();
        
        $data['_view'] = 'sdb_task_type/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new sdb_task_type
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('task_type_active','Task Type Active','required');
		$this->form_validation->set_rules('task_type_name','Task Type Name','required|max_length[100]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'task_type_active' => $this->input->post('task_type_active'),
				'task_type_name' => $this->input->post('task_type_name'),
            );
            
            $sdb_task_type_id = $this->Sdb_task_type_model->add_sdb_task_type($params);
            redirect('sdb_task_type/index');
        }
        else
        {            
            $data['_view'] = 'sdb_task_type/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a sdb_task_type
     */
    function edit($task_type_id)
    {   
        // check if the sdb_task_type exists before trying to edit it
        $data['sdb_task_type'] = $this->Sdb_task_type_model->get_sdb_task_type($task_type_id);
        
        if(isset($data['sdb_task_type']['task_type_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('task_type_active','Task Type Active','required');
			$this->form_validation->set_rules('task_type_name','Task Type Name','required|max_length[100]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'task_type_active' => $this->input->post('task_type_active'),
					'task_type_name' => $this->input->post('task_type_name'),
                );

                $this->Sdb_task_type_model->update_sdb_task_type($task_type_id,$params);            
                redirect('sdb_task_type/index');
            }
            else
            {
                $data['_view'] = 'sdb_task_type/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The sdb_task_type you are trying to edit does not exist.');
    } 

    /*
     * Deleting sdb_task_type
     */
    function remove($task_type_id)
    {
        $sdb_task_type = $this->Sdb_task_type_model->get_sdb_task_type($task_type_id);

        // check if the sdb_task_type exists before trying to delete it
        if(isset($sdb_task_type['task_type_id']))
        {
            $this->Sdb_task_type_model->delete_sdb_task_type($task_type_id);
            redirect('sdb_task_type/index');
        }
        else
            show_error('The sdb_task_type you are trying to delete does not exist.');
    }
    
}
