<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_notification_type extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sdb_notification_type_model');
    }
}
