<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_task_comment extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sdb_task_comment_model');
    } 

    /*
     * Listing of sdb_task_comment
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('sdb_task_comment/index?');
        $config['total_rows'] = $this->Sdb_task_comment_model->get_all_sdb_task_comment_count();
        $this->pagination->initialize($config);

        $data['sdb_task_comment'] = $this->Sdb_task_comment_model->get_all_sdb_task_comment($params);
        
        $data['_view'] = 'sdb_task_comment/index';
        $this->load->view('layouts/main',$data);
    }
}
