<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_station_status extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sdb_staion_status_model');
    } 

    /*
     * Listing of sdb_station_status
     */
    function index()
    {
        $data['sdb_station_status'] = $this->Sdb_station_statu_model->get_all_sdb_station_status();
        
        $data['_view'] = 'sdb_station_statu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new sdb_station_statu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'station_status_name' => $this->input->post('station_status_name'),
				'station_status_active' => $this->input->post('station_status_active'),
				'station_status_createdate' => $this->input->post('station_status_createdate'),
            );
            
            $sdb_station_statu_id = $this->Sdb_station_statu_model->add_sdb_station_status($params);
            redirect('sdb_station_statu/index');
        }
        else
        {            
            $data['_view'] = 'sdb_station_statu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a sdb_station_statu
     */
    function edit($station_status_id)
    {   
        // check if the sdb_station_statu exists before trying to edit it
        $data['sdb_station_statu'] = $this->Sdb_station_statu_model->get_sdb_station_status($station_status_id);
        
        if(isset($data['sdb_station_statu']['station_status_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'station_status_name' => $this->input->post('station_status_name'),
					'station_status_active' => $this->input->post('station_status_active'),
					'station_status_create_date' => $this->input->post('station_status_create_date'),
                );

                $this->Sdb_station_statu_model->update_sdb_station_status($station_status_id,$params);            
                redirect('sdb_station_statu/index');
            }
            else
            {
                $data['_view'] = 'sdb_station_statu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The sdb_station_statu you are trying to edit does not exist.');
    } 

    /*
     * Deleting sdb_station_statu
     */
    function remove($station_status_id)
    {
        $sdb_station_statu = $this->Sdb_station_statu_model->get_sdb_station_statu($station_status_id);

        // check if the sdb_station_statu exists before trying to delete it
        if(isset($sdb_station_statu['station_status_id']))
        {
            $this->Sdb_station_statu_model->delete_sdb_station_statu($station_status_id);
            redirect('sdb_station_statu/index');
        }
        else
            show_error('The sdb_station_status you are trying to delete does not exist.');
    }
    
}
