<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_task_detail extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sdb_task_detail_model');
    } 

    /*
     * Listing of sdb_task_details
     */
    function index()
    {
        $data['sdb_task_details'] = $this->Sdb_task_detail_model->get_all_sdb_task_details();
        
        $data['_view'] = 'sdb_task_detail/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new sdb_task_detail
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'task_id' => $this->input->post('task_id'),
				'task_user_id_receive' => $this->input->post('task_user_id_receive'),
				'task_details_content' => $this->input->post('task_details_content'),
				'infrastructure_id' => $this->input->post('infrastructure_id'),
            );
            
            $sdb_task_detail_id = $this->Sdb_task_detail_model->add_sdb_task_detail($params);
            redirect('sdb_task_detail/index');
        }
        else
        {            
            $data['_view'] = 'sdb_task_detail/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a sdb_task_detail
     */
    function edit($task_details_id)
    {   
        // check if the sdb_task_detail exists before trying to edit it
        $data['sdb_task_detail'] = $this->Sdb_task_detail_model->get_sdb_task_detail($task_details_id);
        
        if(isset($data['sdb_task_detail']['task_details_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'task_id' => $this->input->post('task_id'),
					'task_user_id_receive' => $this->input->post('task_user_id_receive'),
					'task_details_content' => $this->input->post('task_details_content'),
					'infrastructure_id' => $this->input->post('infrastructure_id'),
                );

                $this->Sdb_task_detail_model->update_sdb_task_detail($task_details_id,$params);            
                redirect('sdb_task_detail/index');
            }
            else
            {
                $data['_view'] = 'sdb_task_detail/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The sdb_task_detail you are trying to edit does not exist.');
    } 

    /*
     * Deleting sdb_task_detail
     */
    function remove($task_details_id)
    {
        $sdb_task_detail = $this->Sdb_task_detail_model->get_sdb_task_detail($task_details_id);

        // check if the sdb_task_detail exists before trying to delete it
        if(isset($sdb_task_detail['task_details_id']))
        {
            $this->Sdb_task_detail_model->delete_sdb_task_detail($task_details_id);
            redirect('sdb_task_detail/index');
        }
        else
            show_error('The sdb_task_detail you are trying to delete does not exist.');
    }
    
}
