<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Sdb_checkin extends Admin_Controller{
  function __construct()
  {
    parent::__construct();
    $this->load->model('Sdb_checkin_model');
    $this->load->model('Sdb_distance_model');
  } 
  public function changefile()
  {
    $this->load->helper('directory');

    $m_d=$_SERVER['DOCUMENT_ROOT']."/application/models/";
    $m_d = "./application/models/";
    // var_dump($m_d);
    $m_f=directory_map($m_d,1,false);
    // var_dump($m_f);
    foreach ($m_f as $f){

      // var_dump($f);
      if(preg_match("/(.*)\.php$/",$f)){
        $code = rename($m_d.$f,$m_d.ucwords($f));
        var_dump($code);


      }

    }
  }
    /*
     * Listing of sdb_checkin
     */
    function index()
    {
      $params['limit'] = RECORDS_PER_PAGE; 
      $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

      $config = $this->config->item('pagination');
      $config['base_url'] = site_url('sdb_checkin/index?');
      $config['total_rows'] = $this->Sdb_checkin_model->get_all_sdb_checkin_count();
      $this->pagination->initialize($config);

      $data['sdb_checkin'] = $this->Sdb_checkin_model->get_all_sdb_checkin($params);

      $data['_view'] = 'sdb_checkin/index';
      $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new sdb_checkin
     */
    function add()
    {   
      if(isset($_POST) && count($_POST) > 0) {   
        $params = array(
          'u_group_c_distance_id' => $this->input->post('u_group_c_distance_id'),
          'user_group_id' => $this->input->post('user_group_id'),
          'user_id' => $this->input->post('user_id'),
          'is_checkin' => $this->input->post('is_checkin'),
          'checkin_lat' => $this->input->post('checkin_lat'),
          'checkin_long' => $this->input->post('checkin_long'),
          'checkin_create_date' => $this->input->post('checkin_create_date'),
          'checkin_location' => $this->input->post('checkin_location'),
        );

        $sdb_checkin_id = $this->Sdb_checkin_model->add_sdb_checkin($params);
        redirect('sdb_checkin/index');
      } else {            
        $data['_view'] = 'sdb_checkin/add';
        $this->load->view('layouts/main',$data);
      }
    }  

    /*
     * Editing a sdb_checkin
     */
    function edit($checkin_id)
    {   
        // check if the sdb_checkin exists before trying to edit it
      $data['sdb_checkin'] = $this->Sdb_checkin_model->get_sdb_checkin($checkin_id);

      if(isset($data['sdb_checkin']['checkin_id']))
      {
        if(isset($_POST) && count($_POST) > 0)     
        {   
          $params = array(
           'u_group_c_distance_id' => $this->input->post('u_group_c_distance_id'),
           'user_group_id' => $this->input->post('user_group_id'),
           'user_id' => $this->input->post('user_id'),
           'is_checkin' => $this->input->post('is_checkin'),
           'checkin_lat' => $this->input->post('checkin_lat'),
           'checkin_long' => $this->input->post('checkin_long'),
           'checkin_create_date' => $this->input->post('checkin_create_date'),
           'checkin_location' => $this->input->post('checkin_location'),
         );

          $this->Sdb_checkin_model->update_sdb_checkin($checkin_id,$params);            
          redirect('sdb_checkin/index');
        }
        else
        {
          $data['_view'] = 'sdb_checkin/edit';
          $this->load->view('layouts/main',$data);
        }
      }
      else
        show_error('The sdb_checkin you are trying to edit does not exist.');
    } 

    /*
     * Deleting sdb_checkin
     */
    function remove($checkin_id)
    {
      $sdb_checkin = $this->Sdb_checkin_model->get_sdb_checkin($checkin_id);

        // check if the sdb_checkin exists before trying to delete it
      if(isset($sdb_checkin['checkin_id']))
      {
        $this->Sdb_checkin_model->delete_sdb_checkin($checkin_id);
        redirect('sdb_checkin/index');
      }
      else
        show_error('The sdb_checkin you are trying to delete does not exist.');
    }
    

    function supervisor()
    {

      $data['all_distance'] = $this->Sdb_distance_model->get_all_sdb_distance();
      
      $data['_view'] = 'sdb_checkin/supervisor';

      $this->load->view('layouts/main',$data);
    }


    function get_checkin_by_distance($distance_id = 0)
    {
      $this->load->model('Sdb_checkin_history_model');
      $list_checkin = $this->Sdb_checkin_history_model->get_all_sdb_checkin_history_by_distance($distance_id);
      $this->api_support->set_Reponse($list_checkin, 200 );
    }
    function get_all_checkin_by_distance()
    {
      $this->load->model('Sdb_checkin_history_model');
      $list_checkin = $this->Sdb_checkin_history_model->get_all_sdb_checkin_history_1();
      $this->api_support->set_Reponse($list_checkin, 200 );
    }
  }

