<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_task_img extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sdb_task_img_model');
    } 

    /*
     * Listing of sdb_task_img
     */
    function index()
    {
        $data['sdb_task_img'] = $this->Sdb_task_img_model->get_all_sdb_task_img();
        
        $data['_view'] = 'sdb_task_img/index';
        $this->load->view('layouts/main',$data);
    }
}
