<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_notification_history extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sdb_notification_history_model');
    } 

    /*
     * Listing of sdb_notification_history
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('sdb_notification_history/index?');
        $config['total_rows'] = $this->Sdb_notification_history_model->get_all_sdb_notification_history_count();
        $this->pagination->initialize($config);

        $data['sdb_notification_history'] = $this->Sdb_notification_history_model->get_all_sdb_notification_history($params);
        
        $data['_view'] = 'sdb_notification_history/index';
        $this->load->view('layouts/main',$data);
    }
}
