<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Sdb_c_distance_c_checkin extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sdb_c_distance_c_checkin_model');
    } 

    /*
     * Listing of sdb_c_distance_c_checkin
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('sdb_c_distance_c_checkin/index?');
        $config['total_rows'] = $this->Sdb_c_distance_c_checkin_model->get_all_sdb_c_distance_c_checkin_count();
        $this->pagination->initialize($config);

        $data['sdb_c_distance_c_checkin'] = $this->Sdb_c_distance_c_checkin_model->get_all_sdb_c_distance_c_checkin($params);
        
        $data['_view'] = 'sdb_c_distance_c_checkin/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new sdb_c_distance_c_checkin
     */
    function add()
    {   
        $this->load->library('form_validation');

        $this->form_validation->set_rules('c_distance_c_checkin_location','C Distance C checkin Location','required|max_length[200]');
        $this->form_validation->set_rules('c_distance_c_checkin_lat','C Distance C checkin Lat','required|numeric');
        $this->form_validation->set_rules('c_distance_c_checkin_long','C Distance C checkin Long','required|numeric');
        $this->form_validation->set_rules('c_distance_c_checkin_cretae_date','C Distance C checkin Cretae Date','required');
        $this->form_validation->set_rules('checkin_distance_id','Checkin Distance Id','required');

        if($this->form_validation->run())     
        {   
            $params = array(
                'checkin_distance_id' => $this->input->post('checkin_distance_id'),
                'c_distance_c_checkin_location' => $this->input->post('c_distance_c_checkin_location'),
                'c_distance_c_checkin_lat' => $this->input->post('c_distance_c_checkin_lat'),
                'c_distance_c_checkin_long' => $this->input->post('c_distance_c_checkin_long'),
                'c_distance_c_checkin_cretae_date' => $this->input->post('c_distance_c_checkin_cretae_date'),
            );
            
            $sdb_c_distance_c_checkin_id = $this->Sdb_c_distance_c_checkin_model->add_sdb_c_distance_c_checkin($params);
            redirect('sdb_c_distance_c_checkin/index');
        }
        else
        {
         $this->load->model('Sdb_checkin_distance_model');
         $data['all_sdb_checkin_distance'] = $this->Sdb_checkin_distance_model->get_all_sdb_checkin_distance();

         $data['_view'] = 'sdb_c_distance_c_checkin/add';
         $this->load->view('layouts/main',$data);
     }
 }  

    /*
     * Editing a sdb_c_distance_c_checkin
     */
    function edit($c_distance_c_checkin_id)
    {   
        // check if the sdb_c_distance_c_checkin exists before trying to edit it
        $data['sdb_c_distance_c_checkin'] = $this->Sdb_c_distance_c_checkin_model->get_sdb_c_distance_c_checkin($c_distance_c_checkin_id);
        
        if(isset($data['sdb_c_distance_c_checkin']['c_distance_c_checkin_id']))
        {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('c_distance_c_checkin_location','C Distance C checkin Location','required|max_length[200]');
            $this->form_validation->set_rules('c_distance_c_checkin_lat','C Distance C checkin Lat','required|numeric');
            $this->form_validation->set_rules('c_distance_c_checkin_long','C Distance C checkin Long','required|numeric');
            $this->form_validation->set_rules('c_distance_c_checkin_cretae_date','C Distance C checkin Cretae Date','required');
            $this->form_validation->set_rules('checkin_distance_id','Checkin Distance Id','required');

            if($this->form_validation->run())     
            {   
                $params = array(
                   'checkin_distance_id' => $this->input->post('checkin_distance_id'),
                   'c_distance_c_checkin_location' => $this->input->post('c_distance_c_checkin_location'),
                   'c_distance_c_checkin_lat' => $this->input->post('c_distance_c_checkin_lat'),
                   'c_distance_c_checkin_long' => $this->input->post('c_distance_c_checkin_long'),
                   'c_distance_c_checkin_cretae_date' => $this->input->post('c_distance_c_checkin_cretae_date'),
               );

                $this->Sdb_c_distance_c_checkin_model->update_sdb_c_distance_c_checkin($c_distance_c_checkin_id,$params);            
                redirect('sdb_c_distance_c_checkin/index');
            }
            else
            {
                $this->load->model('Sdb_checkin_distance_model');
                $data['all_sdb_checkin_distance'] = $this->Sdb_checkin_distance_model->get_all_sdb_checkin_distance();

                $data['_view'] = 'sdb_c_distance_c_checkin/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The sdb_c_distance_c_checkin you are trying to edit does not exist.');
    } 

    /*
     * Deleting sdb_c_distance_c_checkin
     */
    function remove($c_distance_c_checkin_id)
    {
        $sdb_c_distance_c_checkin = $this->Sdb_c_distance_c_checkin_model->get_sdb_c_distance_c_checkin($c_distance_c_checkin_id);

        // check if the sdb_c_distance_c_checkin exists before trying to delete it
        if(isset($sdb_c_distance_c_checkin['c_distance_c_checkin_id']))
        {
            $this->Sdb_c_distance_c_checkin_model->delete_sdb_c_distance_c_checkin($c_distance_c_checkin_id);
            redirect('sdb_c_distance_c_checkin/index');
        }
        else
            show_error('The sdb_c_distance_c_checkin you are trying to delete does not exist.');
    }


    function ajax_get_point_checkin_get($checkin_distance_id = 0) {
        
        $reponse =  $this->Sdb_c_distance_c_checkin_model->get_all_sdb_c_distance_c_checkin_by($location_id);
        $this->api_support->set_Reponse($reponse, 200 );
    }

}
