<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Sdb_trouble extends Admin_Controller{
  function __construct()
  {
    parent::__construct();

    $this->load->model('sdb_user_group_model');
    $this->load->model('sdb_user_model');
    $this->load->model('Sdb_trouble_sub_model');
    $this->load->model('Sdb_trouble_sub_comment_model');
    $this->load->model('Sdb_trouble_obj_model');
    $this->load->model('Sdb_trouble_status_model');
    
  } 

  function index()
  {
   $params['limit'] = 5; 
   $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

   $config = $this->config->item('pagination');
   $config['base_url'] = site_url('sdb_trouble/index?');
   $config['total_rows'] = $this->Sdb_trouble_obj_model->get_all_sdb_trouble_obj_count();
   $this->pagination->initialize($config);


   $data['sdb_troubles'] = $this->Sdb_trouble_obj_model->get_all_trouble_obj();
   $data['all_sdb_user_group'] = $this->sdb_user_group_model->get_all_sdb_user_group();
   $data['all_sdb_user'] = $this->sdb_user_model->get_all_sdb_user();
   $data['total_count'] = $config['total_rows'];
   $data['_view'] = 'sdb_trouble/index';
   $this->load->view('layouts/main',$data);
 }


 function add() {
  $this->load->library('form_validation');
  $this->form_validation->set_rules('trouble_name','Trouble Name','required|max_length[100]');
  $this->form_validation->set_rules('trouble_status_id','Trouble Status Id','required|integer');
  $this->form_validation->set_rules('trouble_slug','Trouble Slug','required|max_length[50]');
  $this->form_validation->set_rules('location_id','Location Id','required|integer');
  $this->form_validation->set_rules('trouble_type_id','Trouble Type Id','required|integer');
  $this->form_validation->set_rules('active','Active','required');
  $this->form_validation->set_rules('trouble_detail','Trouble Detail','required');
  $this->form_validation->set_rules('trouble_location','Trouble Location','required');

  if($this->form_validation->run())     
  {   
    $params = array(
      'trouble_status_id' => $this->input->post('trouble_status_id'),
      'location_id' => $this->input->post('location_id'),
      'trouble_type_id' => $this->input->post('trouble_type_id'),
      'trouble_name' => $this->input->post('trouble_name'),
      'trouble_slug' => $this->input->post('trouble_slug'),
      'active' => $this->input->post('active'),
      'user_group_id' => $this->input->post('user_group_id'),
      'user_id' => $this->input->post('user_id'),
      'trouble_detail' => $this->input->post('trouble_detail'),
      'trouble_location' => $this->input->post('trouble_location'),
    );

    $sdb_trouble_id = $this->Sdb_trouble_obj_model->add_sdb_trouble($params);
    redirect('sdb_trouble/index');
  }
  else
  {
   $this->load->model('Sdb_trouble_statu_model');
   $data['all_sdb_trouble_status'] = $this->Sdb_trouble_statu_model->get_all_sdb_trouble_status();

   $this->load->model('Sdb_location_model');
   $data['all_sdb_location'] = $this->Sdb_location_model->get_all_sdb_location();

   $this->load->model('Sdb_trouble_type_model');
   $data['all_sdb_trouble_type'] = $this->Sdb_trouble_type_model->get_all_sdb_trouble_type();

   $data['_view'] = 'sdb_trouble/add';
   $this->load->view('layouts/main',$data);
 }
}  

function comment($trouble_obj_id = 0)
{
  $data['trouble_info'] = $this->Sdb_trouble_obj_model->get_trouble_obj_by_id($trouble_obj_id);
  $params['limit'] = 10;
  $params['offset'] = 0;
  $data['trouble_commnet'] = $this->Sdb_trouble_obj_model->get_trouble_obj_comment($trouble_obj_id,$params);
  $data['_view'] = 'sdb_trouble/comment';
  $this->load->view('layouts/main',$data);          
}

function edit($id) {
  $data['sdb_trouble'] = $this->Sdb_trouble_obj_model->get_sdb_trouble($id);

  if(isset($data['sdb_trouble']['id']))
  {
    $this->load->library('form_validation');

    $this->form_validation->set_rules('trouble_name','Trouble Name','required|max_length[100]');
    $this->form_validation->set_rules('trouble_status_id','Trouble Status Id','required|integer');
    $this->form_validation->set_rules('trouble_slug','Trouble Slug','required|max_length[50]');
    $this->form_validation->set_rules('location_id','Location Id','required|integer');
    $this->form_validation->set_rules('trouble_type_id','Trouble Type Id','required|integer');
    $this->form_validation->set_rules('active','Active','required');
    $this->form_validation->set_rules('trouble_detail','Trouble Detail','required');
    $this->form_validation->set_rules('trouble_location','Trouble Location','required');

    if($this->form_validation->run())     
    {   
      $params = array(
       'trouble_status_id' => $this->input->post('trouble_status_id'),
       'location_id' => $this->input->post('location_id'),
       'trouble_type_id' => $this->input->post('trouble_type_id'),
       'trouble_name' => $this->input->post('trouble_name'),
       'trouble_slug' => $this->input->post('trouble_slug'),
       'active' => $this->input->post('active'),
       'user_group_id' => $this->input->post('user_group_id'),
       'user_id' => $this->input->post('user_id'),
       'trouble_detail' => $this->input->post('trouble_detail'),
       'trouble_location' => $this->input->post('trouble_location'),
     );

      $this->Sdb_trouble_obj_model->update_sdb_trouble($id,$params);            
      redirect('sdb_trouble/index');
    }
    else
    {
      $this->load->model('Sdb_trouble_statu_model');
      $data['all_sdb_trouble_status'] = $this->Sdb_trouble_statu_model->get_all_sdb_trouble_status();

      $this->load->model('Sdb_location_model');
      $data['all_sdb_location'] = $this->Sdb_location_model->get_all_sdb_location();

      $this->load->model('Sdb_trouble_type_model');
      $data['all_sdb_trouble_type'] = $this->Sdb_trouble_type_model->get_all_sdb_trouble_type();

      $data['_view'] = 'sdb_trouble/edit';
      $this->load->view('layouts/main',$data);
    }
  }
  else
    show_error('The sdb_trouble you are trying to edit does not exist.');
} 


function task($id) {
  $data['sdb_trouble'] = $this->Sdb_trouble_obj_model->get_sdb_trouble($id);

  if(isset($data['sdb_trouble']['id']))
  {
    $this->load->library('form_validation');
    if($this->form_validation->run()) {   
      $params = array(
       'trouble_status_id' => $this->input->post('trouble_status_id'),
       'location_id' => $this->input->post('location_id'),
       'trouble_type_id' => $this->input->post('trouble_type_id'),
       'trouble_name' => $this->input->post('trouble_name'),
       'trouble_slug' => $this->input->post('trouble_slug'),
       'active' => $this->input->post('active'),
       'user_group_id' => $this->input->post('user_group_id'),
       'user_id' => $this->input->post('user_id'),
       'trouble_detail' => $this->input->post('trouble_detail'),
       'trouble_location' => $this->input->post('trouble_location'),
     );
      $this->Sdb_trouble_obj_model->update_sdb_trouble($id,$params);            
      redirect('sdb_trouble/index');
    } else {
      $this->load->model('Sdb_trouble_statu_model');
      $data['all_sdb_trouble_status'] = $this->Sdb_trouble_statu_model->get_all_sdb_trouble_status();
      $this->load->model('Sdb_location_model');
      $data['all_sdb_location'] = $this->Sdb_location_model->get_all_sdb_location();
      $this->load->model('Sdb_trouble_type_model');
      $data['all_sdb_trouble_type'] = $this->Sdb_trouble_type_model->get_all_sdb_trouble_type();
      $data['_view'] = 'sdb_trouble/task';
      $this->load->view('layouts/main',$data);
    }
  }
  else
    show_error('The sdb_trouble you are trying to edit does not exist.');
} 


function remove($id)
{
  $sdb_trouble = $this->Sdb_trouble_obj_model->get_sdb_trouble($id);
  if(isset($sdb_trouble['id']))
  {
    $this->Sdb_trouble_obj_model->delete_sdb_trouble($id);
    redirect('sdb_trouble/index');
  }
  else
    show_error('The sdb_trouble you are trying to delete does not exist.');
}

function ajax_put_task_trouble()
{
  $user_revice_id = $this->input->post('user_revice_id');
  $user_group_revice_id = $this->input->post('user_group_revice_id');
  $date_start = $this->input->post('date_start');
  $date_end = $this->input->post('date_end');
  $trouble_id = $this->input->post('trouble_id');

  $params = array(
   'user_revice_id' => $user_revice_id,
   'user_group_revice_id' => $user_group_revice_id,
   'trouble_date_start' => $date_start,
   'trouble_date_end' => $date_end,
   'trouble_status_id' => 2
 );
  $code = $this->Sdb_trouble_obj_model->update_sdb_trouble($trouble_id,$params);        
  if($code) {
    $this->api_support->set_Reponse('update success', 200 );
  }else {
    $this->api_support->set_Reponse('update falied', 400 ,'',false);
  }

}    

function  detail($trouble_obj_id = 0)
{
  $data['trouble_info'] = $this->Sdb_trouble_obj_model->get_trouble_obj_by_id($trouble_obj_id);
  $params['limit'] = 5;
  $params['offset'] = 0;
  $data['trouble_commnet'] = $this->Sdb_trouble_obj_model->get_trouble_obj_comment($trouble_obj_id,$params);
  $data['_view'] = 'sdb_trouble/detail';
  $this->load->view('layouts/iframe',$data);
}


function add_comment() {

  $trouble_obj_id = $this->input->post('trouble_obj_id');
  $trouble_obj_comment = $this->input->post('trouble_obj_comment');

  if(empty($trouble_obj_id)) {
    redirect('sdb_trouble/index','refresh');
  }

  $params__ = array(
   'user_id' => USER_ID,
   'trouble_obj_comment' => $trouble_obj_comment,
   'trouble_obj_id' => $trouble_obj_id,
 );

  $this->Sdb_trouble_obj_model->add_trouble_obj_comment($params__); 
        
  redirect('sdb_trouble/comment/'.$trouble_obj_id);
}

}
