<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_checkin_statu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sdb_checkin_statu by checkin_status_id
     */
    function get_sdb_checkin_statu($checkin_status_id)
    {
        return $this->db->get_where('sdb_checkin_status',array('checkin_status_id'=>$checkin_status_id))->row_array();
    }
        
    /*
     * Get all sdb_checkin_status
     */
    function get_all_sdb_checkin_status()
    {
        $this->db->order_by('checkin_status_id', 'desc');
        return $this->db->get('sdb_checkin_status')->result_array();
    }
        
    /*
     * function to add new sdb_checkin_statu
     */
    function add_sdb_checkin_statu($params)
    {
        $this->db->insert('sdb_checkin_status',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sdb_checkin_statu
     */
    function update_sdb_checkin_statu($checkin_status_id,$params)
    {
        $this->db->where('checkin_status_id',$checkin_status_id);
        return $this->db->update('sdb_checkin_status',$params);
    }
    
    /*
     * function to delete sdb_checkin_statu
     */
    function delete_sdb_checkin_statu($checkin_status_id)
    {
        return $this->db->delete('sdb_checkin_status',array('checkin_status_id'=>$checkin_status_id));
    }
}
