<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_user_type_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sdb_user_type by user_type_id
     */
    function get_sdb_user_type($user_type_id)
    {
        return $this->db->get_where('sdb_user_type',array('user_type_id'=>$user_type_id))->row_array();
    }
        
    /*
     * Get all sdb_user_type
     */
    function get_all_sdb_user_type()
    {
        $this->db->order_by('user_type_level');
        return $this->db->get('sdb_user_type')->result_array();
    }
        
    /*
     * function to add new sdb_user_type
     */
    function add_sdb_user_type($params)
    {
        $this->db->insert('sdb_user_type',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sdb_user_type
     */
    function update_sdb_user_type($user_type_id,$params)
    {
        $this->db->where('user_type_id',$user_type_id);
        return $this->db->update('sdb_user_type',$params);
    }
    
    /*
     * function to delete sdb_user_type
     */
    function delete_sdb_user_type($user_type_id)
    {
        return $this->db->delete('sdb_user_type',array('user_type_id'=>$user_type_id));
    }
}
