<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_c_distance_c_checkin_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    

      function get_all_sdb_c_distance_c_checkin_by($checkin_distance_id)
    {
        return $this->db->get_where('sdb_c_distance_c_checkin',array('checkin_distance_id' => $checkin_distance_id))->result_array();
    }


    /*
     * Get sdb_c_distance_c_checkin by c_distance_c_checkin_id
     */
    function get_sdb_c_distance_c_checkin($c_distance_c_checkin_id)
    {
        return $this->db->get_where('sdb_c_distance_c_checkin',array('c_distance_c_checkin_id'=>$c_distance_c_checkin_id))->row_array();
    }
    
    /*
     * Get all sdb_c_distance_c_checkin count
     */
    function get_all_sdb_c_distance_c_checkin_count()
    {
        $this->db->from('sdb_c_distance_c_checkin');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all sdb_c_distance_c_checkin
     */
    function get_all_sdb_c_distance_c_checkin($params = array())
    {
        $this->db->order_by('c_distance_c_checkin_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('sdb_c_distance_c_checkin')->result_array();
    }
        
    /*
     * function to add new sdb_c_distance_c_checkin
     */
    function add_sdb_c_distance_c_checkin($params)
    {
        $this->db->insert('sdb_c_distance_c_checkin',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sdb_c_distance_c_checkin
     */
    function update_sdb_c_distance_c_checkin($c_distance_c_checkin_id,$params)
    {
        $this->db->where('c_distance_c_checkin_id',$c_distance_c_checkin_id);
        return $this->db->update('sdb_c_distance_c_checkin',$params);
    }
    
    /*
     * function to delete sdb_c_distance_c_checkin
     */
    function delete_sdb_c_distance_c_checkin($c_distance_c_checkin_id)
    {
        return $this->db->delete('sdb_c_distance_c_checkin',array('c_distance_c_checkin_id'=>$c_distance_c_checkin_id));
    }

     function delete_sdb_c_distance_c_checkin_by($checkin_distance_id)
    {
        return $this->db->delete('sdb_c_distance_c_checkin',array('checkin_distance_id'=>$checkin_distance_id));
    }
}
