<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_img_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sdb_img by id
     */
    function get_sdb_img($id)
    {
        return $this->db->get_where('sdb_img',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all sdb_img
     */
    function get_all_sdb_img()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('sdb_img')->result_array();
    }
        
    /*
     * function to add new sdb_img
     */
    function add_sdb_img($params)
    {
        $this->db->insert('sdb_img',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sdb_img
     */
    function update_sdb_img($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('sdb_img',$params);
    }
    
    /*
     * function to delete sdb_img
     */
    function delete_sdb_img($id)
    {
        return $this->db->delete('sdb_img',array('id'=>$id));
    }
}
