<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Sdb_infrastructure_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function get_sdb_infrastructure_count()
    {
        $this->db->from('sdb_infrastructures');
        return $this->db->count_all_results();
    }


    function get_sdb_infrastructure($infrastructure_id)
    {
        return $this->db->get_where('sdb_infrastructures', array('infrastructure_id' => $infrastructure_id))->row_array();
    }



    function get_all_sdb_infrastructures($params = [])
    {
        $this->db->from('sdb_infrastructures');
        $this->db->join('sdb_location', 'sdb_location.location_id = sdb_infrastructures.location_id', 'left');

        $this->db->join('sdb_distance', 'sdb_distance.distance_id = sdb_infrastructures.distance_id', 'left');
        $this->db->join('sdb_infrastructures_category', 'sdb_infrastructures_category.infrastructures_category_id = sdb_infrastructures.infrastructures_category_id');
        $this->db->join('sdb_infrastructures_status', 'sdb_infrastructures_status.infrastructure_status_id = sdb_infrastructures.infrastructure_status_id');
        $this->db->order_by('infrastructure_id', 'desc');

        if (isset($params) && !empty($params)) {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get()->result_array();
    }
    function get_all_sdb_infrastructures_by_distance($distance_id)
    {
        $this->db->from('sdb_infrastructures');
        $this->db->join('sdb_location', 'sdb_location.location_id = sdb_infrastructures.location_id', 'left');
        $this->db->join('sdb_stations', 'sdb_stations.station_id = sdb_infrastructures.station_id', 'left');
        $this->db->join('sdb_distance', 'sdb_distance.distance_id = sdb_infrastructures.distance_id', 'left');
        $this->db->join('sdb_infrastructures_category', 'sdb_infrastructures_category.infrastructures_category_id = sdb_infrastructures.infrastructures_category_id');
        $this->db->join('sdb_infrastructures_status', 'sdb_infrastructures_status.infrastructure_status_id = sdb_infrastructures.infrastructure_status_id', 'left');
        $this->db->where(array('sdb_infrastructures.distance_id' => $distance_id));
        $this->db->order_by('infrastructure_id', 'desc');
        return $this->db->get()->result_array();
    }


    function get_all_by_distance_and_category($distance_id, $infrastructures_category_id)
    {
        $this->db->from('sdb_infrastructures');
        $this->db->join('sdb_location','sdb_location.location_id = sdb_infrastructures.location_id','left');
        $this->db->join('sdb_stations','sdb_stations.station_id = sdb_infrastructures.station_id','left');
        $this->db->join('sdb_distance','sdb_distance.distance_id = sdb_infrastructures.distance_id','left');
        $this->db->join('sdb_infrastructures_category','sdb_infrastructures_category.infrastructures_category_id = sdb_infrastructures.infrastructures_category_id');
        $this->db->join('sdb_infrastructures_status','sdb_infrastructures_status.infrastructure_status_id = sdb_infrastructures.infrastructure_status_id','left');
        $this->db->where(array(
                'sdb_infrastructures.distance_id' => $distance_id,
                'sdb_infrastructures.infrastructures_category_id' => $infrastructures_category_id,
            ));

        $this->db->order_by('infrastructure_id', 'desc');
        return $this->db->get()->result_array();
    }


    function get_all_sdb_infrastructures_by_location($location_id)
    {
        $this->db->from('sdb_infrastructures');
        $this->db->join('sdb_location', 'sdb_location.location_id = sdb_infrastructures.location_id', 'left');
        $this->db->join('sdb_stations', 'sdb_stations.station_id = sdb_infrastructures.station_id', 'left');
        $this->db->join('sdb_distance', 'sdb_distance.distance_id = sdb_infrastructures.distance_id', 'left');

        $this->db->join('sdb_infrastructures_category', 'sdb_infrastructures_category.infrastructures_category_id = sdb_infrastructures.infrastructures_category_id');

        $this->db->join('sdb_infrastructures_status', 'sdb_infrastructures_status.infrastructure_status_id = sdb_infrastructures.infrastructure_status_id', 'left');

        $this->db->where(array('sdb_infrastructures.location_id' => $location_id));
        $this->db->order_by('infrastructure_id', 'desc');
        return $this->db->get()->result_array();
    }


    function get_all_sdb_infrastructures_by_station($station_id)
    {
        $this->db->from('sdb_infrastructures');
        $this->db->join('sdb_location', 'sdb_location.location_id = sdb_infrastructures.location_id', 'left');
        $this->db->join('sdb_stations', 'sdb_stations.station_id = sdb_infrastructures.station_id', 'left');
        $this->db->join('sdb_distance', 'sdb_distance.distance_id = sdb_infrastructures.distance_id', 'left');
        $this->db->join('sdb_infrastructures_status', 'sdb_infrastructures_status.infrastructure_status_id = sdb_infrastructures.infrastructure_status_id', 'left');
        $this->db->where(array('sdb_infrastructures.station_id' => $station_id));
        $this->db->order_by('infrastructure_id', 'desc');
        return $this->db->get()->result_array();
    }


    /*
     * function to add new sdb_infrastructure
     */
    function add_sdb_infrastructure($params)
    {
        $this->db->insert('sdb_infrastructures', $params);
        return $this->db->insert_id();
    }

    function add_sdb_infrastructure_one_time($arr_params)
    {
        $this->db->insert_batch_dup('sdb_infrastructures', $arr_params);
        return $this->db->insert_id();
    }

    /*
     * function to update sdb_infrastructure
     */
    function update_sdb_infrastructure($infrastructure_id, $params)
    {
        $this->db->where('infrastructure_id', $infrastructure_id);
        return $this->db->update('sdb_infrastructures', $params);
    }

    /*
     * function to delete sdb_infrastructure
     */
    function delete_sdb_infrastructure($infrastructure_id)
    {
        return $this->db->delete('sdb_infrastructures', array('infrastructure_id' => $infrastructure_id));
    }


    function create_infrastructure_obj($infrastructure_category_id = 0)
    {
        $this->db->from('sdb_infrastructures_category');
        $this->db->join('sdb_infrastructures_category_obj', 'sdb_infrastructures_category_obj.infrastructures_category_id = sdb_infrastructures_category. infrastructures_category_id');

        $this->db->where(array('sdb_infrastructures_category.infrastructures_category_id' => $infrastructure_category_id));
        $this->db->where(array('sdb_infrastructures_category_obj.infrastructures_category_obj_active' => 1));

        return $this->db->get()->result_array();
    }
}
