<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_comment_project_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sdb_comment_project by comment_project_id
     */
    function get_sdb_comment_project($comment_project_id)
    {
        return $this->db->get_where('sdb_comment_project',array('comment_project_id'=>$comment_project_id))->row_array();
    }
    
    /*
     * Get all sdb_comment_project count
     */
    function get_all_sdb_comment_project_count()
    {
        $this->db->from('sdb_comment_project');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all sdb_comment_project
     */
    function get_all_sdb_comment_project($params = array())
    {
        $this->db->order_by('comment_project_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('sdb_comment_project')->result_array();
    }
        
    /*
     * function to add new sdb_comment_project
     */
    function add_sdb_comment_project($params)
    {
        $this->db->insert('sdb_comment_project',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sdb_comment_project
     */
    function update_sdb_comment_project($comment_project_id,$params)
    {
        $this->db->where('comment_project_id',$comment_project_id);
        return $this->db->update('sdb_comment_project',$params);
    }
    
    /*
     * function to delete sdb_comment_project
     */
    function delete_sdb_comment_project($comment_project_id)
    {
        return $this->db->delete('sdb_comment_project',array('comment_project_id'=>$comment_project_id));
    }
}
