<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_user_group_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sdb_user_group by user_group_id
     */
    function get_sdb_user_group($user_group_id)
    {
        return $this->db->get_where('sdb_user_group',array('user_group_id'=>$user_group_id))->row_array();
    }
        
    /*
     * Get all sdb_user_group
     */
    function get_all_sdb_user_group()
    {
        $this->db->order_by('user_group_id', 'desc');
        return $this->db->get('sdb_user_group')->result_array();
    }
        
    /*
     * function to add new sdb_user_group
     */
    function add_sdb_user_group($params)
    {
        $this->db->insert('sdb_user_group',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sdb_user_group
     */
    function update_sdb_user_group($user_group_id,$params)
    {
        $this->db->where('user_group_id',$user_group_id);
        return $this->db->update('sdb_user_group',$params);
    }
    
    /*
     * function to delete sdb_user_group
     */
    function delete_sdb_user_group($user_group_id)
    {
        return $this->db->delete('sdb_user_group',array('user_group_id'=>$user_group_id));
    }
}
