<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_notification_type_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sdb_notification_type by notification_type_id
     */
    function get_sdb_notification_type($notification_type_id)
    {
        return $this->db->get_where('sdb_notification_type',array('notification_type_id'=>$notification_type_id))->row_array();
    }
        
    /*
     * Get all sdb_notification_type
     */
    function get_all_sdb_notification_type()
    {
        $this->db->order_by('notification_type_id', 'desc');
        return $this->db->get('sdb_notification_type')->result_array();
    }
        
    /*
     * function to add new sdb_notification_type
     */
    function add_sdb_notification_type($params)
    {
        $this->db->insert('sdb_notification_type',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sdb_notification_type
     */
    function update_sdb_notification_type($notification_type_id,$params)
    {
        $this->db->where('notification_type_id',$notification_type_id);
        return $this->db->update('sdb_notification_type',$params);
    }
    
    /*
     * function to delete sdb_notification_type
     */
    function delete_sdb_notification_type($notification_type_id)
    {
        return $this->db->delete('sdb_notification_type',array('notification_type_id'=>$notification_type_id));
    }
}
