<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Sdb_c_distance_u_group_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    
    function get_sdb_c_distance_u_group($c_distance_u_group_id)
    {
        return $this->db->get_where('sdb_c_distance_u_group',array('c_distance_u_group_id'=>$c_distance_u_group_id))->row_array();
    }

    function get_all_sdb_c_distance_u_group()
    {
        $this->db->order_by('c_distance_u_group_id', 'desc');
        return $this->db->get('sdb_c_distance_u_group')->result_array();
    }

    function get_all_sdb_c_distance_u_group_distance()
    {
        $this->db->from('sdb_c_distance_u_group');
        $this->db->join('sdb_checkin_distance','sdb_checkin_distance.checkin_distance_id = sdb_c_distance_u_group.checkin_distance_id');
        $this->db->join('sdb_user_group','sdb_user_group.user_group_id = sdb_c_distance_u_group.user_group_id');
        $this->db->order_by('c_distance_u_group_id', 'desc');
        return $this->db->get()->result_array();
    }

    function get_sdb_checkin_distance_and_point($checkin_distance_id = 0)
    {



        $query_Con = 'CONCAT("[",GROUP_CONCAT( DISTINCT CONCAT("{\"checkin_distance_id","\":",cdug.checkin_distance_id,",\"checkin_distance_name","\":\"",cdug.checkin_distance_name,"\"}")),"]") as points';
        $query = $this->db->query("SELECT *,$query_Con 
            FROM sdb_checkin_distance cdug 
            join sdb_c_distance_c_checkin cdcc
            ON cdug.checkin_distance_id = cdcc.checkin_distance_id
            where 
            cdug.checkin_distance_id = $checkin_distance_id
            ");

        return  $query->row_array();
    }


    
    function add_sdb_c_distance_u_group($params)
    {
        $this->db->insert('sdb_c_distance_u_group',$params);
        return $this->db->insert_id();
    }

    
    function update_sdb_c_distance_u_group($c_distance_u_group_id,$params)
    {
        $this->db->where('c_distance_u_group_id',$c_distance_u_group_id);
        return $this->db->update('sdb_c_distance_u_group',$params);
    }
    
 
    function delete_sdb_c_distance_u_group($c_distance_u_group_id)
    {
        return $this->db->delete('sdb_c_distance_u_group',array('c_distance_u_group_id'=>$c_distance_u_group_id));
    }
}
