<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_log_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sdb_log by log_id
     */
    function get_sdb_log($log_id)
    {
        return $this->db->get_where('sdb_log',array('log_id'=>$log_id))->row_array();
    }
        
    /*
     * Get all sdb_log
     */
    function get_all_sdb_log()
    {
        $this->db->order_by('log_id', 'desc');
        return $this->db->get('sdb_log')->result_array();
    }
        
    /*
     * function to add new sdb_log
     */
    function add_sdb_log($params)
    {
        $this->db->insert('sdb_log',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sdb_log
     */
    function update_sdb_log($log_id,$params)
    {
        $this->db->where('log_id',$log_id);
        return $this->db->update('sdb_log',$params);
    }
    
    /*
     * function to delete sdb_log
     */
    function delete_sdb_log($log_id)
    {
        return $this->db->delete('sdb_log',array('log_id'=>$log_id));
    }
}
