<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Sdb_checkin_history_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    

    function get_sdb_checkin_history($checkin_history_id)
    {
        return $this->db->get_where('sdb_checkin_history',array('checkin_history_id'=>$checkin_history_id))->row_array();
    }
    

    function get_sdb_checkin_history_details($checkin_history_id)
    {

        $this->db->from('sdb_checkin_history');
        $this->db->join('sdb_user','sdb_user.user_id = sdb_checkin_history.user_id');
        $this->db->join('sdb_user_group','sdb_user_group.user_group_id = sdb_checkin_history.user_group_id');
        $this->db->join('sdb_checkin_distance','sdb_checkin_distance.checkin_distance_id = sdb_checkin_history.checkin_distance_id');
        $this->db->join('sdb_c_distance_c_checkin','sdb_c_distance_c_checkin.c_distance_c_checkin_id = sdb_checkin_history.c_distance_c_checkin_id');
        $this->db->where(array('sdb_checkin_history.checkin_history_id'=>$checkin_history_id));
        return $this->db->get()->row_array();

    }

    function get_sdb_checkin_history_details_new($c_distance_c_checkin_id)
    {

        $this->db->from('sdb_checkin_history');
        $this->db->join('sdb_user','sdb_user.user_id = sdb_checkin_history.user_id');
        $this->db->join('sdb_user_group','sdb_user_group.user_group_id = sdb_checkin_history.user_group_id');
        $this->db->join('sdb_checkin_distance','sdb_checkin_distance.checkin_distance_id = sdb_checkin_history.checkin_distance_id');
        $this->db->join('sdb_c_distance_c_checkin','sdb_c_distance_c_checkin.c_distance_c_checkin_id = sdb_checkin_history.c_distance_c_checkin_id');
        $this->db->where(array('sdb_checkin_history.c_distance_c_checkin_id'=>$c_distance_c_checkin_id));
        $this->db->order_by('checkin_history_id', 'desc');
        return $this->db->get()->result_array();

    }

    

    function get_all_sdb_checkin_history_count()
    {
        $this->db->from('sdb_checkin_history');
        return $this->db->count_all_results();
    }
    
    

    function get_all_sdb_checkin_history_count_by_user($user_id)
    {
        $this->db->from('sdb_checkin_history');
        $this->db->where(['user_id' => $user_id]);
        return $this->db->count_all_results();
    }
    
    

    function get_all_sdb_checkin_history($params = array())
    {
        $this->db->from('sdb_checkin_history');
        $this->db->join('sdb_checkin_status','sdb_checkin_status.checkin_status_id = sdb_checkin_history.checkin_status_id');
        $this->db->join('sdb_user','sdb_user.user_id = sdb_checkin_history.user_id');
        $this->db->join('sdb_c_distance_c_checkin','sdb_c_distance_c_checkin.c_distance_c_checkin_id = sdb_checkin_history.c_distance_c_checkin_id');
        $this->db->join('sdb_checkin_distance','sdb_checkin_distance.checkin_distance_id = sdb_checkin_history.checkin_distance_id');
        $this->db->order_by('checkin_history_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get()->result_array();
    }

    function get_all_sdb_checkin_history_1()
    {
     $this->db->from('sdb_checkin_history');
     $this->db->join('sdb_checkin_status','sdb_checkin_status.checkin_status_id = sdb_checkin_history.checkin_status_id');
     $this->db->join('sdb_user','sdb_user.user_id = sdb_checkin_history.user_id');
     $this->db->join('sdb_c_distance_c_checkin','sdb_c_distance_c_checkin.c_distance_c_checkin_id = sdb_checkin_history.c_distance_c_checkin_id');
     $this->db->join('sdb_stations','sdb_stations.station_id = sdb_checkin_history.station_id','left');

     $this->db->join('sdb_checkin_distance','sdb_checkin_distance.checkin_distance_id = sdb_checkin_history.checkin_distance_id');
     $this->db->join('sdb_distance','sdb_distance.distance_id = sdb_checkin_distance.distance_id','left');
     $this->db->order_by('checkin_history_id', 'desc');
     return $this->db->get()->result_array();
 }


 function add_sdb_checkin_history($params)
 {
    $this->db->insert('sdb_checkin_history',$params);
    return $this->db->insert_id();
}


function update_sdb_checkin_history($checkin_history_id,$params)
{
    $this->db->where('checkin_history_id',$checkin_history_id);
    return $this->db->update('sdb_checkin_history',$params);
}


function delete_sdb_checkin_history($checkin_history_id)
{
    return $this->db->delete('sdb_checkin_history',array('checkin_history_id'=>$checkin_history_id));
}


function get_all_sdb_checkin_history_by_user($user_id, $params = [])
{
    $this->db->from('sdb_checkin_history');
    $this->db->join('sdb_checkin_status','sdb_checkin_status.checkin_status_id = sdb_checkin_history.checkin_status_id');
    $this->db->join('sdb_user','sdb_user.user_id = sdb_checkin_history.user_id');
    $this->db->join('sdb_user_group','sdb_user_group.user_group_id = sdb_checkin_history.user_group_id');
    $this->db->join('sdb_c_distance_c_checkin','sdb_c_distance_c_checkin.c_distance_c_checkin_id = sdb_checkin_history.c_distance_c_checkin_id');
    $this->db->join('sdb_checkin_distance','sdb_checkin_distance.checkin_distance_id = sdb_checkin_history.checkin_distance_id');
    $this->db->join('sdb_location','sdb_location.location_id = sdb_checkin_distance.location_id');
    $this->db->order_by('checkin_history_id', 'desc');
    $this->db->where(array('sdb_user.user_id'=>$user_id));

        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }


    return $this->db->get()->result_array();
}


function get_all_sdb_checkin_history_by_user_sender($user_id)
{
    $this->db->from('sdb_checkin_history');
    $this->db->join('sdb_checkin_status','sdb_checkin_status.checkin_status_id = sdb_checkin_history.checkin_status_id');
    $this->db->join('sdb_user','sdb_user.user_id = sdb_checkin_history.user_id');
    $this->db->join('sdb_user_group','sdb_user_group.user_group_id = sdb_checkin_history.user_group_id');

    $this->db->join('sdb_c_distance_c_checkin','sdb_c_distance_c_checkin.c_distance_c_checkin_id = sdb_checkin_history.c_distance_c_checkin_id');
    $this->db->join('sdb_checkin_distance','sdb_checkin_distance.checkin_distance_id = sdb_checkin_history.checkin_distance_id');
    $this->db->join('sdb_location','sdb_location.location_id = sdb_checkin_distance.location_id');
    $this->db->order_by('checkin_history_id', 'desc');
    // $this->db->where(array('sdb_checkin_history.user_sender_id'=>$user_id));
    return $this->db->get()->result_array();
}

function get_all_sdb_checkin_history_by_checkin_distance($checkin_distance_id)
{
    $this->db->from('sdb_checkin_history');
    $this->db->join('sdb_checkin_status','sdb_checkin_status.checkin_status_id = sdb_checkin_history.checkin_status_id');
    $this->db->join('sdb_user','sdb_user.user_id = sdb_checkin_history.user_id');
    $this->db->join('sdb_c_distance_c_checkin','sdb_c_distance_c_checkin.c_distance_c_checkin_id = sdb_checkin_history.c_distance_c_checkin_id');

    $this->db->join('sdb_checkin_distance','sdb_checkin_distance.checkin_distance_id = sdb_checkin_history.checkin_distance_id');
    $this->db->order_by('checkin_history_id', 'desc');
    $this->db->where(array('sdb_checkin_distance.checkin_distance_id'=>$checkin_distance_id));
    return $this->db->get()->result_array();
}
function get_all_sdb_checkin_history_by_distance($distance_id)
{
    $this->db->from('sdb_checkin_history');
    $this->db->join('sdb_checkin_status','sdb_checkin_status.checkin_status_id = sdb_checkin_history.checkin_status_id');
    $this->db->join('sdb_user','sdb_user.user_id = sdb_checkin_history.user_id');
    $this->db->join('sdb_c_distance_c_checkin','sdb_c_distance_c_checkin.c_distance_c_checkin_id = sdb_checkin_history.c_distance_c_checkin_id');
    $this->db->join('sdb_stations','sdb_stations.station_id = sdb_checkin_history.station_id','left');

    $this->db->join('sdb_checkin_distance','sdb_checkin_distance.checkin_distance_id = sdb_checkin_history.checkin_distance_id');
    $this->db->join('sdb_distance','sdb_distance.distance_id = sdb_checkin_distance.distance_id','left');
    $this->db->order_by('checkin_history_id', 'desc');
    $this->db->where(array('sdb_checkin_distance.distance_id'=>$distance_id));
    return $this->db->get()->result_array();
}

function get_all_sdb_checkin_history_by_location($location_id)
{
    $this->db->from('sdb_checkin_history');
    $this->db->join('sdb_checkin_status','sdb_checkin_status.checkin_status_id = sdb_checkin_history.checkin_status_id');
    $this->db->join('sdb_user','sdb_user.user_id = sdb_checkin_history.user_id');
    $this->db->join('sdb_c_distance_c_checkin','sdb_c_distance_c_checkin.c_distance_c_checkin_id = sdb_checkin_history.c_distance_c_checkin_id');
    $this->db->join('sdb_checkin_distance','sdb_checkin_distance.checkin_distance_id = sdb_checkin_history.checkin_distance_id');
    $this->db->join('sdb_location','sdb_location.location_id = sdb_checkin_distance.location_id');
    $this->db->order_by('checkin_history_id', 'desc');
    $this->db->where(array('sdb_location.location_id'=>$location_id));
    return $this->db->get()->result_array();
}




}
