<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Sdb_infrastructure_modified_history_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sdb_infrastructure_modified_history by trouble_status_id
     */
    function get_sdb_infrastructure_modified_history($trouble_status_id)
    {
        return $this->db->get_where('sdb_infrastructures_modified_history',array('trouble_status_id'=>$trouble_status_id))->row_array();
    }

    /*
     * Get all sdb_infrastructure_modified_history
     */
    function get_all_sdb_infrastructure_modified_history()
    {
        // $this->db->order_by('infrastructure_modified_history_id', 'desc');
        return $this->db->get('sdb_infrastructures_modified_history')->result_array();
    }

    /*
     * function to add new sdb_infrastructure_modified_history
     */
    function add_sdb_infrastructure_modified_history($params)
    {
        $this->db->insert('sdb_infrastructures_modified_history',$params);
        return $this->db->insert_id();
    }



    /*
     * function to update sdb_infrastructure_modified_history
     */
    function update_sdb_infrastructure_modified_history($infrastructure_modified_history_id,$params)
    {
        $this->db->where('infrastructure_modified_history_id',$station_id);
        return $this->db->update('sdb_infrastructures_modified_history',$params);
    }
    
    /*
     * function to delete sdb_infrastructure_modified_history
     */
    function delete_sdb_infrastructure_modified_history($infrastructure_modified_history_id)
    {
        return $this->db->delete('sdb_infrastructure_modified_history',array('infrastructure_modified_history_id'=>$trouble_status_id));
    }
}
