<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Sdb_infrastructures_category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get sdb_infrastructures_category by infrastructures_category_id
     */
    function get_sdb_infrastructures_category($infrastructures_category_id)
    {
        return $this->db->get_where('sdb_infrastructures_category', array('infrastructures_category_id' => $infrastructures_category_id))->row_array();
    }
    function get_sdb_infrastructures_category_obj_by_infrastructures($infrastructures_category_id)
    {
        return $this->db->get_where('sdb_infrastructures_category_obj', array('infrastructures_category_id' => $infrastructures_category_id))->result_array();
    }

    function get_all_sdb_infrastructures_category_count()
    {
        $this->db->from('sdb_infrastructures_category');
        return $this->db->count_all_results();
    }

    /*
     * Get all sdb_infrastructures_category
     */
    function get_all_sdb_infrastructures_category($params = array())
    {
        $this->db->order_by('infrastructures_category_id', 'desc');
        $this->db->where(array('infrastructures_category_active' => 1));
        if (isset($params) && !empty($params)) {
            $this->db->limit($params['limit'], $params['offset']);
        }

        return $this->db->get('sdb_infrastructures_category')->result_array();
    }

    function get_infrastructures_category_import($params = array())
    {
        
        $this->db->where($params);
        return $this->db->get('sdb_infrastructures_category')->result_array();
    }


    function get_all_sdb_infrastructures_category_by_parent($type_parents_type_id)
    {
        return $this->db->get_where('sdb_infrastructures_category', array('type_parents_type_id' => $type_parents_type_id))->result_array();
    }

    /*
     * function to add new sdb_infrastructures_category
     */
    function add_sdb_infrastructures_category($params)
    {
        $this->db->insert('sdb_infrastructures_category', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update sdb_infrastructures_category
     */
    function update_sdb_infrastructures_category($infrastructures_category_id, $params)
    {
        $this->db->where('infrastructures_category_id', $infrastructures_category_id);
        return $this->db->update('sdb_infrastructures_category', $params);
    }

    /*
     * function to delete sdb_infrastructures_category
     */
    function delete_sdb_infrastructures_category($infrastructures_category_id)
    {
        return $this->db->delete('sdb_infrastructures_category', array('infrastructures_category_id' => $infrastructures_category_id));
    }
}
