<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_disrepair_category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
        
    function get_all()
    {
        return $this->db->get('sdb_disrepair_category')->result_array();
    }

}
