<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sdb_location_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sdb_location by location_id
     */
    function get_sdb_location($location_id)
    {
        return $this->db->get_where('sdb_location',array('location_id'=>$location_id))->row_array();
    }
    
    /*
     * Get all sdb_location count
     */
    function get_all_sdb_location_count()
    {
        $this->db->from('sdb_location');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all sdb_location
     */
    function get_all_sdb_location($params = array())
    {
        $this->db->order_by('location_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('sdb_location')->result_array();
    }
        
    /*
     * function to add new sdb_location
     */
    function add_sdb_location($params)
    {
        $this->db->insert('sdb_location',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sdb_location
     */
    function update_sdb_location($location_id,$params)
    {
        $this->db->where('location_id',$location_id);
        return $this->db->update('sdb_location',$params);
    }
    
    /*
     * function to delete sdb_location
     */
    function delete_sdb_location($location_id)
    {
        return $this->db->delete('sdb_location',array('location_id'=>$location_id));
    }
}
