<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Sdb_distance_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sdb_distance by distance_id
     */
    function get_sdb_distance($distance_id)
    {
        return $this->db->get_where('sdb_distance',array('distance_id'=>$distance_id))->row_array();
    }
    
    /*
     * Get all sdb_distance count
     */
    function get_all_sdb_distance_count()
    {
        $this->db->from('sdb_distance');
        return $this->db->count_all_results();
    }

    /*
     * Get all sdb_distance
     */
    function get_all_sdb_distance($params = array())
    {

     $this->db->from('sdb_distance');
     $this->db->join('sdb_location', 'sdb_location.location_id = sdb_distance.location_id');
     $this->db->order_by('distance_id', 'desc');
     if(isset($params) && !empty($params))
     {
        $this->db->limit($params['limit'], $params['offset']);
    }
    return $this->db->get()->result_array();
}

function get_all_sdb_distance_by_location($location_id)
{

    $this->db->from('sdb_distance');
    $this->db->join('sdb_location', 'sdb_location.location_id = sdb_distance.location_id');
    $this->db->where(array('sdb_location.location_id' => $location_id));
    $this->db->order_by('distance_id', 'desc');
    if(isset($params) && !empty($params))
    {
        $this->db->limit($params['limit'], $params['offset']);
    }
    return $this->db->get()->result_array();
}


function add_sdb_distance($params)
{
    $this->db->insert('sdb_distance',$params);
    return $this->db->insert_id();
}


function update_sdb_distance($distance_id,$params)
{
    $this->db->where('distance_id',$distance_id);
    return $this->db->update('sdb_distance',$params);
}


function delete_sdb_distance($distance_id)
{
    return $this->db->delete('sdb_distance',array('distance_id'=>$distance_id));
}
}
